const passages = [
  "Habits shape our lives more than we realize. From brushing our teeth to checking our phones, routines guide our behavior. The brain prefers efficiency, so it automates repeated actions. This is why forming good habits is crucial. Once established, they require less effort to maintain. Breaking bad habits, however, demands conscious effort and replacement with positive ones. Understanding the habit loop—cue, routine, reward—can help us rewire our behavior. Whether it's exercising daily or reading before bed, small changes compound over time.",
  "The forest was alive with sound. Birds chirped overhead, leaves rustled underfoot, and a distant stream gurgled softly. Sunlight filtered through the canopy, casting dappled shadows on the mossy ground. Each step revealed something new—a squirrel darting up a tree, a mushroom nestled beside a fallen log, or a spider weaving its intricate web. The air smelled of pine and damp earth. It was a place of quiet magic, where time slowed and nature whispered its secrets.",
  "In a world dominated by screens, taking a digital detox is more important than ever. Constant notifications, endless scrolling, and digital overload can lead to stress and burnout. Disconnecting for a day—or even an hour—can refresh the mind. Reading a book, going for a walk, or simply sitting in silence helps restore balance. It’s not about rejecting technology, but about using it mindfully. A detox reminds us that presence is powerful, and real life happens beyond the screen.",
  "Whiskers twitching, the cat crept silently across the room. Her eyes locked onto the fluttering curtain, convinced it hid something mysterious. With a sudden leap, she pounced—only to find nothing but air. Unfazed, she turned her attention to a crumpled paper ball. Batting it across the floor, she chased it with wild abandon. Her antics were a blend of grace and chaos, a reminder that curiosity, even when it leads nowhere, is its own reward.",
  "Tea has traveled across centuries and continents. Originating in China, it was once a medicinal brew. Over time, it became a cultural staple—from Japanese tea ceremonies to British afternoon tea. Each region developed its own rituals and flavors. Green, black, oolong, and herbal varieties offer distinct experiences. Beyond taste, tea symbolizes hospitality, reflection, and connection. Whether sipped alone or shared with friends, it’s a drink steeped in tradition and comfort.",
  "Storytelling is one of humanity’s oldest traditions. Long before books or films, people gathered around fires to share tales of heroes, gods, and everyday life. Stories carry lessons, preserve culture, and spark imagination. A well-told story can transport listeners to distant lands or inspire them to see their own world differently. Today, storytelling thrives in novels, podcasts, movies, and even marketing campaigns. At its core, it remains about connection—bridging experiences between teller and audience.",
  "The ocean covers more than two-thirds of our planet, yet much of it remains unexplored. Beneath the waves lie ecosystems teeming with life, from tiny plankton to massive whales. Coral reefs, often called the rainforests of the sea, support incredible biodiversity. Scientists believe countless species are still undiscovered. The ocean also regulates climate and provides food for billions. Protecting it is vital, as pollution and overfishing threaten its delicate balance",
  "A productive day often begins with a mindful morning routine. Some people start with meditation, others with exercise, and many with a strong cup of coffee. Establishing rituals helps set the tone for the hours ahead. Writing down goals, stretching, or simply enjoying quiet moments can boost focus and energy. The key is consistency. A routine doesn’t need to be elaborate; even small habits, repeated daily, can create a sense of stability and purpose",
  "Friendship is one of life’s greatest treasures. True friends offer support during hardships and celebrate joys with sincerity. Unlike family, friendships are chosen, making them uniquely special. They thrive on trust, respect, and shared experiences. A simple conversation with a friend can ease stress or spark laughter. In a fast-paced world, nurturing friendships requires effort, but the rewards—companionship, understanding, and belonging—are immeasurable.",
  "Every invention begins with curiosity. Someone asks, “What if?” and pursues an answer. From the wheel to the smartphone, inventions have reshaped human life. The process often involves trial, error, and persistence. Many inventors faced skepticism before their ideas gained acceptance. Innovation thrives where imagination meets determination. Today, technology evolves rapidly, but the spirit of invention remains timeless: solving problems and improving lives.",
  "Climbing a mountain is both a physical and mental challenge. The path is steep, the air thin, and the journey long. Yet each step brings a sense of accomplishment. Reaching the summit offers breathtaking views and a reminder of resilience. Mountains symbolize obstacles in life—difficult but conquerable. The climb teaches patience, endurance, and appreciation for nature’s grandeur.",
  "Books are gateways to knowledge and imagination. They allow readers to travel through time, explore distant lands, and meet unforgettable characters. A single page can spark curiosity or change perspective. Libraries, filled with countless volumes, are treasure troves of wisdom. In the digital age, e-books and audiobooks make reading more accessible, but the magic of holding a physical book remains unmatched.",
  "Music is a universal language. It transcends borders, cultures, and generations. A melody can evoke joy, sadness, or nostalgia. From classical symphonies to modern pop, music reflects human emotion and creativity. It accompanies celebrations, rituals, and everyday life. For many, music is therapy—a way to heal, express, or simply escape. Its rhythm connects us to one another and to ourselves.",
  "Sleep is essential for health and productivity. During rest, the body repairs itself and the mind processes memories. Lack of sleep can lead to fatigue, poor concentration, and weakened immunity. Establishing good sleep habits—like maintaining a regular schedule and limiting screen time before bed—improves quality of rest. In a busy world, sleep is often undervalued, yet it remains one of the most powerful tools for well-being.",
  "Adventure is about stepping into the unknown. It could be traveling to a new country, trying a new hobby, or meeting new people. Adventures challenge comfort zones and spark growth. They create stories worth telling and memories worth keeping. While risk is part of adventure, so is reward—the thrill of discovery and the joy of experience. Life becomes richer when lived with a spirit of exploration."
];
